#Compilation Dir
APPLICATION_DIR = ../../app

#Makefile for the selected MCU Project
MCU_MAKE_DIR = MCU/G474/

#If required GCC compilator path
#GCC_PATH = ~/github/STM-Linux/gcc-arm-none-eabi-9-2020-q2-update/bin/

# Changed By Key
# Linked flags for compilation iwth CPP for now i was not able to find a better way : 
# -specs=nano.specs is ptomized for MCU code size and Speed but it's causing somehow issue during liking
# to be bale to compile -specs=nanospecs is prelaced with -specs=nosys.specs
# this is resulting on a bigger code but working with C++
C_SPECS_FLAG = -specs=nano.specs
CPP_SPECS_FLAG = -specs=nosys.specs
#Set one of the frla for compilation
SPECS_FLAG = $(CPP_SPECS_FLAG)

#Set CPP source
CPP_SOURCES += Core/Src/Cpp/app_main.cpp
